main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('trainer/', views.trainer_index, name='index'),
    path('trainer/<int:trainer_id>/', views.trainer_details, name='details'),
    path('trainer/create/', views.TrainerCreate.as_view(), name='trainer_create'),
    path('trainer/<int:pk>/update/', views.TrainerUpdate.as_view(), name='trainer_update'),
    path('trainer/<int:pk>/delete/', views.TrainerDelete.as_view(), name='trainer_delete'),
    path('trainer/<int:trainer_id>/add_pokemon/', views.add_pokemon, name='add_pokemon'),
    path('moves/', views.MoveList.as_view(), name='moves_index'),
    path('moves/<int:move_id>/', views.move_details, name='moves_detail'),
    path('moves/create/', views.MoveCreate.as_view(), name='moves_create'),
    path('moves/<int:pk>/update/', views.MoveUpdate.as_view(), name='moves_update'),
    path('moves/<int:pk>/delete/', views.MoveDelete.as_view(), name='moves_delete'),
    path('moves/<int:move_id>/assoc_pokemon/', views.assoc_pokemon, name='assoc_pokemon'),
    path('moves/<int:move_id>/remove_pokemon/<int:pokemon_id>/', views.remove_pokemon, name='remove_pokemon'),
]

pokemoncollector/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse


class Trainer(models.Model):
    name = models.CharField(max_length=30)
    badges = models.IntegerField("Badges Won")
    is_gym_leader = models.BooleanField("Gym Leader", default=False)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('details', kwargs={'trainer_id': self.id})


class Move(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50, default="Normal")
    power_point = models.IntegerField("PP")
    power = models.IntegerField()
    accuracy = models.IntegerField()

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('moves_detail', kwargs={'pk': self.id})


class Pokemon(models.Model):
    pokedex_number = models.IntegerField("Pokedex Number")
    name = models.CharField(max_length=30)
    nickname = models.CharField(max_length=30, default='', blank=True, null=True)
    type = models.CharField("Pokemon Type", max_length=50, default='')

    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    moves = models.ManyToManyField(Move)

    def __str__(self):
        return f"{self.name} #{self.pokedex_number}"

    def get_absolute_url(self):
        return reverse('details', kwargs={'pokemon_id': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Pokemon


class PokemonForm(ModelForm):
    class Meta:
        model = Pokemon
        fields = ['pokedex_number', 'name', 'nickname', 'type']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Trainer, Move, Pokemon
from .forms import PokemonForm


# Create your views here.
def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def trainer_index(request):
    trainer = Trainer.objects.all()
    return render(request, 'trainer/index.html', {
        'trainer': trainer,
    })


def trainer_details(request, trainer_id):
    trainer = Trainer.objects.get(id=trainer_id)
    pokemon_form = PokemonForm()
    return render(request, 'trainer/details.html', {
        'trainer': trainer,
        'pokemon_form': pokemon_form,
    })


def assoc_pokemon(request, move_id):
    pokemon_id = str(request.POST['pokemon_id'])
    Pokemon.objects.get(id=pokemon_id).moves.add(move_id)
    return redirect('moves_detail', move_id=move_id)


def remove_pokemon(request, move_id, pokemon_id):
    Pokemon.objects.get(id=pokemon_id).moves.remove(move_id)
    return redirect('moves_detail', move_id)


def add_pokemon(request, trainer_id):
    form = PokemonForm(request.POST)
    if form.is_valid():
        new_pokemon = form.save(commit=False)
        new_pokemon.trainer_id = trainer_id
        new_pokemon.save()
    return redirect('details', trainer_id=trainer_id)


def move_details(request, move_id):
    move = Move.objects.get(id=move_id)
    pokemon_list = Pokemon.objects.all()
    return render(request, 'main_app/move_detail.html', {
        'move': move,
        'pokemon_list': pokemon_list
    })


class TrainerCreate(CreateView):
    model = Trainer
    fields = '__all__'


class TrainerUpdate(UpdateView):
    model = Trainer
    fields = '__all__'


class TrainerDelete(DeleteView):
    model = Trainer
    success_url = '/trainer'


class MoveList(ListView):
    model = Move


class MoveCreate(CreateView):
    model = Move
    fields = '__all__'


class MoveUpdate(UpdateView):
    model = Move
    fields = '__all__'


class MoveDelete(DeleteView):
    model = Move
    success_url = '/moves'

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>Pokémon Collector</h1>
  <hr />
  <p>Gotta Catch 'Em All!!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pokémon Collector</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<header class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <ul>
                <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Pokémon Collector</a></li>
            </ul>
            <ul class="right">
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'moves_create' %}">Create Moves</a></li>
                <li><a href="{% url 'moves_index' %}">All Moves</a></li>
                <li><a href="{% url 'trainer_create' %}">Add Trainer</a></li>
                <li><a href="{% url 'index' %}">All Trainers</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
<footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Pokémon Collector &nbsp;</div>
</footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Pokémon Collector Home!</h1>
  <hr />
  <p>Hire the Pokémon Collector!</p> 
{% endblock %}

main_app/templates/main_app/move_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'moves_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/move_detail.html
{% extends 'base.html' %}
{% block content %}

    <h1>Move Details</h1>

    <div class="row">
        <div class="col s6 col-offset-3">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ move.name }}</span>
                    <p>Type: {{ move.type }}</p>
                    <p>PP: {{ move.power_point }}</p>
                    <p>Power: {{ move.power }}</p>
                    <p>Accuracy: {{ move.accuracy }}%</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'moves_update' move.id %}">Edit</a>
                    <a href="{% url 'moves_delete' move.id %}">Delete</a>
                </div>
            </div>
        </div>
        <div class="col s6 col-offset-3 center-align">
            <form action="{% url 'assoc_pokemon' move.id %}" method="POST">
                {% csrf_token %}
                <select name="pokemon_id" id="{{ pokemon.id }}">
                    <option value="pokemon" selected disabled>Select</option>
                    {% for pokemon in pokemon_list %}
                        <option value="{{ pokemon.id }}"{% if pokemon.id == selected_pokemon_id %} selected {% endif %}>
                            {{ pokemon.name }}
                        </option>
                    {% endfor %}
                </select>
                <label for="{{ pokemon.id }}">Select Pokemon to give Move</label>
                <button class="btn">Add to Pokemon</button>
            </form>
        </div>
    </div>
    <hr>
    <div>
        {% if move.pokemon_set.count %}
            <div class="row">
                {% for pokemon in move.pokemon_set.all %}
                    <div class="col s3 col-offset-3">
                        <form action="{% url 'remove_pokemon' move.id pokemon.id %}"
                              method="POST">
                            {% csrf_token %}
                            <div class="chip">
                                {{ pokemon.name }}
                                <button class="waves-effect waves-light btn red lighten-1">X</button>
                            </div>
                        </form>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <script>
        const selectEl = document.querySelectorAll('select');
        M.FormSelect.init(selectEl)
    </script>
{% endblock %}

main_app/templates/main_app/move_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
    {% else %}
        <h1>Add Move</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/move_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Move List</h1>

{% for move in move_list %}
  <a href="{% url 'moves_detail' move.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ move.name }}</span>
            <p>Type: {{ move.type }}</p>
            <p>PP: {{ move.power_point }}</p>
            <p>Power: {{ move.power }}</p>
            <p>Accuracy: {{ move.accuracy }}%</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/pokemon_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete {{ object.name }}</h1>

  <h4>Are you sure?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' pokemon.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/trainer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete {{ object.name }}</h1>

  <h4>Are you sure?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' trainer.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/trainer_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Trainer</h1>
{% endif %}
<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>
<script>
  const tdElement = document.getElementById('id_is_gym_leader').parentElement;
  const pElement = document.createElement("p");
  const labelElement = document.createElement("label");
  const spanElement = document.createElement("span");
  spanElement.textContent = "Gym Leader?";
  labelElement.appendChild(tdElement.querySelector("input"));
  labelElement.appendChild(spanElement);
  pElement.appendChild(labelElement);
  tdElement.innerHTML = '';
  tdElement.appendChild(pElement);
</script>
{% endblock %}

main_app/templates/trainer/details.html
{% extends 'base.html' %}
{% block content %}

    <h1>Details</h1>

    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ trainer.name }} | {% if trainer.is_gym_leader %}Gym Leader{% else %}
                        Trainer{% endif %}</span>
                    <p>Badges Won: {{ trainer.badges }}
                    </p>
                </div>
                <div class="card-action">
                    <a href="{% url 'trainer_update' trainer.id %}">Edit</a>
                    <a href="{% url 'trainer_delete' trainer.id %}">Delete</a>
                </div>
            </div>
        </div>
        <div class="col s6">
            <form action="{% url 'add_pokemon' trainer.id %}" method="POST">
                {% csrf_token %}
                {{ pokemon_form.as_p }}
                <input type="submit" class="btn" value="Add Pokemon">
            </form>
            <table class="striped">
                <thead>
                <tr>
                    <th>Pokedex #</th>
                    <th>Pokemon</th>
                    <th>Nickname</th>
                    <th>Types</th>
                </tr>
                </thead>
                <tbody>
                {% for pokemon in trainer.pokemon_set.all %}
                    <tr>
                        <td>{{ pokemon.pokedex_number }}</td>
                        <td><a href="https://bulbapedia.bulbagarden.net/wiki/{{ pokemon.name }}_(Pok%C3%A9mon)"
                               target="_blank">{{ pokemon.name }}</a></td>
                        <td>{{ pokemon.nickname }}</td>
                        <td>{{ pokemon.type }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

main_app/templates/trainer/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Trainer List</h1>

{% for t in trainer %}
<div class="card">
  <a href="{% url 'details' t.id %}">
    <div class="card-content">
      <span class="card-title">{{ t.name }} | {% if t.is_gym_leader %}Gym Leader{% else %}Trainer{% endif %}</span>
      <ul>
        <li>Badges Won: {{ t.badges }}</li>
      </ul>
    </div>
  </a>
</div>
{% endfor %}

{% endblock %}